title: Symbolic
author: Jason Morley
email: support@jbmorley.co.uk
description: ""
baseurl: ""
url: "https://symbolic.app"

plugins:
  - jekyll-feed
destination: ../_site

defaults:
  - values:
      layout: "default"
